spring:
  application:
    name: product
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
  flyway:
    enabled: true
    encoding: UTF-8
    schemas: public
    locations: classpath:/db/migration/
    validate-on-migrate: true
    baseline-on-migrate: true

server:
  port: 8181